INSERT INTO user_passwords (
  user_id, password_hash, password_salt, iterations, created_at, updated_at
) VALUES
  ('demo-admin-ava', 'YI+8vTKBTPqA3qvbRcq4Cr2eNqR4Pd4F93Wudlh86Og=', 'yEdGXLSlMS364vopVghAAw==', 100000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('demo-coach-zac', 'V2A6Xh3y50acB2iPKYAG9jplvbb9f4PesiqVsYGASo4=', 'UUWR2GMUj3ZE7cqUhiLqHg==', 100000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('demo-member-joe', 'HuquW3j/oeuXK6LacaLQmH+YLXd1QgMd1abZSH6RHJ0=', 'eQjdNAoIHXdB+AEL6W3tAA==', 100000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('demo-member-sam', 'y4zaEjN0aaNpS+rd5/lx9+qzR+gWST+qB6Vy4LDBGEA=', '1o8DCLQNC1P/+HYbv/qwMg==', 100000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
  password_hash = excluded.password_hash,
  password_salt = excluded.password_salt,
  iterations = excluded.iterations,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO lesson_videos (
  id, member_id, coach_id, uploaded_by_role, title, description,
  coach_notes, coach_private_notes, user_notes, video_type, focus_area,
  swing_type, club, tags_json, session_data_id, storage_path,
  thumbnail_storage_path, file_name, file_size, mime_type, duration,
  lesson_date, publication_status, upload_status, review_status,
  email_status, is_viewed_by_member, lesson_summary, worked_on,
  key_issue, improvement, practice_assignment, recommended_drill,
  member_facing_notes, created_at, updated_at
) VALUES (
  'demo-video-sam-lesson',
  'demo-member-sam',
  'demo-coach-zac',
  'coach',
  'Demo wedge lesson recap',
  'Seeded demo lesson video for Cloudflare R2 playback testing.',
  'Keep pressure moving forward and use the wedge clock to control carry windows.',
  'Coach-only seeded demo notes.',
  '',
  'Lesson Recap',
  'Wedges',
  'Wedge',
  'SW',
  '["demo","wedge","r2"]',
  'demo-session-sand-wedge',
  'lesson-videos/demo-member-sam/demo-video-sam-lesson/video',
  NULL,
  'demo-lesson-video.txt',
  110,
  'text/plain',
  12,
  '2026-07-15',
  'Published',
  'ready',
  'New',
  'Not sent',
  0,
  'Seeded lesson summary for demo playback.',
  'Wedge distance control and start line.',
  'Carry window needs tighter launch consistency.',
  'Use a three-position wedge ladder.',
  'Hit 3 sets of 6 balls at 70, 85, and 100 yards.',
  'Clock wedge ladder with landing-zone scoring.',
  'Watch this recap, then run the wedge ladder before the next session.',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT(id) DO UPDATE SET
  member_id = excluded.member_id,
  coach_id = excluded.coach_id,
  title = excluded.title,
  description = excluded.description,
  coach_notes = excluded.coach_notes,
  coach_private_notes = excluded.coach_private_notes,
  video_type = excluded.video_type,
  focus_area = excluded.focus_area,
  swing_type = excluded.swing_type,
  club = excluded.club,
  tags_json = excluded.tags_json,
  session_data_id = excluded.session_data_id,
  storage_path = excluded.storage_path,
  file_name = excluded.file_name,
  file_size = excluded.file_size,
  mime_type = excluded.mime_type,
  duration = excluded.duration,
  lesson_date = excluded.lesson_date,
  publication_status = excluded.publication_status,
  upload_status = excluded.upload_status,
  lesson_summary = excluded.lesson_summary,
  worked_on = excluded.worked_on,
  key_issue = excluded.key_issue,
  improvement = excluded.improvement,
  practice_assignment = excluded.practice_assignment,
  recommended_drill = excluded.recommended_drill,
  member_facing_notes = excluded.member_facing_notes,
  updated_at = CURRENT_TIMESTAMP;
